name: Deploy api

on:
  push:
    branches: ['main']
    paths:
      - 'Api/**'
      - 'Domain/**'
      - 'SharedKernel/**'
      - 'Terview.sln'

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . -t ${{ vars.DOCKERHUB_USERNAME }}/terview:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the image to Docker Hub
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/terview
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
